#!/bin/python2
import os, sys, time
os.system ('clear')
print ("\33[32;1m")
print ("woy romlah")
time.sleep(1)
print ("i am sorry")
time.sleep(2)
print ("tools sedang bermasalah")
time.sleep(2)
print ("dan sedang di perbaiki oleh admin")
time.sleep(2)
print ("subscribe aja ya lagi ku perbaiki toolsnya")
time.sleep(10)
os.system("xdg-open https://www.youtube.com/channel/UC1rlhLpR7f1ehlvx7IRgEvg")
print ("like dulu ajik")
time.sleep (5)
os.system("echo udahh di perbaiki kok")
print ("inget 500 subs sadap wa")
print ("udah keluar script baru di youtube ku")
